Pansy
DMIRLAB-Group/causal-dmir pull request #10
Opened 2024-05-27 05:18 UTC by Pansyyyy

update utils/kernel/linear.py and utils/kernel/polynomial.py
add utils/independence/tests/test_desp.py and test_fisherz.py and test_kci.py
add utils/kernel/tests/test_gaussian.py and test_linear.py and test_polynomial.py

2024-05-27 05:38 UTC, Pansyyyy commented
update utils/kernel/linear.py and utils/kernel/polynomial.py
add utils/independence/tests/test_desp.py and test_fisherz.py and test_kci.py
add utils/kernel/tests/test_gaussian.py and test_linear.py and test_polynomial.py

2024-05-27 06:35 UTC, miumiujiang12138 reviewed
github本地测试未过，请修改，至少3.7和3.8版本要通过。
![pansy](https://github.com/DMIRLAB-Group/causal-dmir/assets/129245663/e030df90-c79b-43e8-bf47-1eff28940941)

2024-05-27 07:10 UTC, Pansyyyy commented
update utils/kernel/linear.py and utils/kernel/polynomial.py
add utils/independence/tests/test_desp.py
add utils/kernel/tests/test_gaussian.py and test_linear.py and test_polynomial.py

2024-05-28 12:41 UTC, miumiujiang12138 requested changes
没有大问题，主要是把test_gaussian.py中的error修复一下就可以了

2024-05-28 12:41 UTC, miumiujiang12138 commented on causaldmir/utils/kernel/linear.py
我按照注释修改了，然后通过了对应的测试脚本，说明注释建议修改的内容是对的，这边建议把注释的内容，直接改到代码里。

2024-05-28 12:41 UTC, miumiujiang12138 commented on causaldmir/utils/kernel/test/test_gaussian.py
这个test脚本中出现了断言错误
![image](https://github.com/DMIRLAB-Group/causal-dmir/assets/129245663/1a85de4c-bc1b-45e2-b2bd-64a7c57e4f89)
![image](https://github.com/DMIRLAB-Group/causal-dmir/assets/129245663/8f7471dd-b59f-4a9a-83eb-41c8143692ba)

2024-05-28 12:41 UTC, miumiujiang12138 commented on causaldmir/utils/independence/tests/test_desp.py
测试通过

2024-05-28 12:41 UTC, miumiujiang12138 commented on causaldmir/utils/kernel/test/test_linear.py
测试通过

2024-05-28 12:41 UTC, miumiujiang12138 commented on causaldmir/utils/kernel/test/test_polynomial.py
测试通过

2024-05-29 07:40 UTC, Pansyyyy commented
correct assert error

2024-06-24 09:48 UTC, merged