Zzh
DMIRLAB-Group/causal-dmir pull request #13
Opened 2024-05-27 13:44 UTC by zzihuai

2024-05-29 15:02 UTC, miumiujiang12138 requested changes

2024-05-29 15:02 UTC, miumiujiang12138 commented on causaldmir/graph/tests/test_grpah_transform.py
> +            g = txt2graph(f'causaldmir/graph/tests/testdata/dag.{i}.txt')
这个路径好像有点问题，请检查修复一下
![image](https://github.com/DMIRLAB-Group/causal-dmir/assets/129245663/a5031a77-6149-49e4-8086-f07ba41b547b)

2024-06-11 11:09 UTC, zzihuai commented on causaldmir/graph/tests/test_grpah_transform.py
> +            g = txt2graph(f'causaldmir/graph/tests/testdata/dag.{i}.txt')
这里路径貌似并没有问题，脚本也没有报错

2024-06-11 11:29 UTC, zzihuai commented on causaldmir/graph/tests/test_graph.py
> +        g = Graph(x for x in range(10))
已修复

2024-06-14 02:15 UTC, miumiujiang12138 approved these changes

2024-06-14 02:17 UTC, miumiujiang12138 commented on causaldmir/graph/tests/test_grpah_transform.py
> +            g = txt2graph(f'causaldmir/graph/tests/testdata/dag.{i}.txt')
OK，可能是编辑器的问题，vscode这边改成绝对路径后测试也是通过的

2024-06-14 02:17 UTC, miumiujiang12138 commented on causaldmir/graph/tests/test_graph.py
> +        g = Graph(x for x in range(10))
OK，测试通过

2024-06-14 02:18 UTC, merged